### ISSUE TITLE
trying to install on el capitan

### ISSUE THREAD

**Issue by macfree** [ianrrees/macports#1]
Hi,

thanks for doing this by the way, great for me not having that much of compilation experience.

Im trying to port calculix with the following results, can you advise how to proceed or give me an indication of what I should do in order to debug/give you debug information? 

I get some different results compared to the others on the freecad forum: 4 ports parsed instead of 1 and I have to write "sudo port install math/calculix" instead of "sudo port install calculix"

computer name=test =)

///////////////////////////////////
test:Downloads markusenberg$ git clone https://github.com/ianrrees/macports.git
Cloning into 'macports'...
remote: Counting objects: 35, done.
remote: Total 35 (delta 0), reused 0 (delta 0), pack-reused 35
Unpacking objects: 100% (35/35), done.
Checking connectivity... done.
test:Downloads markusenberg$ cd macports/
test:macports markusenberg$ ls
README.md	math
test:macports markusenberg$ portindex
Creating port index in /Users/markusenberg/Downloads/macports
Adding port math/calculix
Adding subport calculix-ccx
Adding subport calculix-cgx
Adding subport calculix-html

Total number of ports parsed:	4 
Ports successfully parsed:	4 
Ports failed:			0 
Up-to-date ports skipped:	0

test:macports markusenberg$ sudo port install calculix
Error: Port calculix not found
test:macports markusenberg$ sudo port install math/calculix
Error: Unable to execute port: Could not open file: /Users/markusenberg/Downloads/macports/math/calculix/Portfile
test:macports markusenberg$ ls math/calculix/
Portfile	files		work
test:macports markusenberg$ 
test:macports markusenberg$ cd math/calculix/files/
test:files markusenberg$ ls
patch-calculix-build.diff	patch-cgx-build.diff		patch-spooles-build.diff
patch-ccx-build.diff		patch-libSNL-build.diff
test:files markusenberg$

**Comment by ianrrees** [comment]
Hi Markus,

       I think your problem is that the new MacPorts repository you've created (~/Downloads/macports/ by the look of things) needs to be added to your MacPorts configuration - see https://guide.macports.org/#development.local-repositories .

Beyond that, you might need to do "sudo port install calculix-ccx" (with the "-ccx" added), can't remember.

You might also want to keep an eye on https://trac.macports.org/ticket/50810 - one of these months it might get pulled in to MacPorts!  -Ian-
